env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  linebreak-style: 0
  no-unused-expressions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
